# SPDX-License-Identifier: Apache-2.0


set(NX_ENABLED 1 BOOL PARENT_SCOPE)

set(NX_SRC_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(NX_BIN_ROOT "${CMAKE_CURRENT_BINARY_DIR}")

set(NX_LIBRARY_PATH ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(NX_RUNTIME_PATH ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(NX_INCLUDE_PATH ${CMAKE_INCLUDE_OUTPUT_DIRECTORY})

set(NX_ONNX_MLIR_SRC_ROOT ${ONNX_MLIR_SRC_ROOT})
set(NX_ONNX_MLIR_BIN_ROOT ${ONNX_MLIR_BIN_ROOT})

add_subdirectory(Dialect)

add_onnx_mlir_library(OMNXAccel
  NxAccelerator.cpp

  EXCLUDE_FROM_OM_LIBS

  INCLUDE_DIRS PUBLIC
  ${ONNX_MLIR_SRC_ROOT}/include
  ${ONNX_MLIR_SRC_ROOT}
  ${NX_ONNX_MLIR_SRC_ROOT}
  ${NX_SRC_ROOT}
  ${NX_BIN_ROOT}
  ${NX_INCLUDE_PATH}

  LINK_LIBS PUBLIC
  onnx
  #OMNXCompilerUtils
  OMAccelerator
  )

  