/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===------------------------ NXCompilerOptions.hpp ---------------------===//
//
// Copyright 2025 Intel Labs.
//
// =============================================================================
//
//
//===----------------------------------------------------------------------===//

#ifndef ONNX_MLIR_NX_COMPILER_OPTIONS_H
#define ONNX_MLIR_NX_COMPILER_OPTIONS_H

#include "llvm/Support/CommandLine.h"

// clang-format off

#define INSTRUMENTSTAGE_ENUM_NX                                               \
    ,                                                                          \
    NX

// clang-format on

#define INSTRUMENTSTAGE_CL_ENUM_NX                                           \
  clEnumVal(Onnx, "Profile for onnx ops. For NX, profile onnx ops before "   \
                  "lowering to zhigh."),                                       \
      clEnumVal(NX, "NX profiling for onnx and zhigh ops.")

#define PROFILEIR_CL_ENUM_NX                                                 \
  , clEnumVal(NX, "Profile operations in ZHighIR generated by "             \
                     "--EmitZHighIR.")

#define OPTREPORT_ENUM_NX , NXUnsupportedOps

#define OPTREPORT_CL_ENUM_NX                                                 \
  , clEnumVal(NXUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on NX.")

#define INSTRUMENTSTAGE_CL_ENUM_NX                                           \
  clEnumVal(Onnx, "Profile for onnx ops. For NX, profile onnx ops before "   \
                  "lowering to zhigh."),                                       \
      clEnumVal(NX, "NX profiling for onnx and zhigh ops.")

#define PROFILEIR_CL_ENUM_NX                                                 \
  , clEnumVal(NX, "Profile operations in ZHighIR generated by "             \
                     "--EmitZHighIR.")

#define OPTREPORT_ENUM_NX , NXUnsupportedOps

#define OPTREPORT_CL_ENUM_NX                                                 \
  , clEnumVal(NXUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on NX.")

namespace onnx_mlir {
typedef enum {
  ExampleA,
  ExampleB,
  ExampleC,
} NXExampleOption;

extern llvm::cl::opt<onnx_mlir::NXExampleOption> nxExample;

} // namespace onnx_mlir
#endif
